apiVersion: v1
kind: Pod
metadata:
  namespace: oss-agent
spec:
  nodeSelector:
    eks.amazonaws.com/nodegroup: eks-oss-presto-dynamic-managed-ng
  serviceAccountName: oss-agent
  containers:
  - name: maven
    image: maven:3.8.6-openjdk-8-slim
    tty: true
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "6Gi"
        cpu: "2000m"
    command:
    - cat
