apiVersion: v1
kind: Pod
metadata:
  namespace: oss-agent
spec:
  nodeSelector:
    eks.amazonaws.com/nodegroup: eks-oss-presto-dynamic-managed-ng
  serviceAccountName: oss-agent
  containers:
  - name: dind
    image: docker:24.0.7-dind-alpine3.19
    securityContext:
      privileged: true
    tty: true
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
